### PR TITLE
Support of Minecraft 1.20.5

### PR DESCRIPTION
**Pull request by atomic-junky**
I added the armadillo scute, the armadillo spawn egg, the wolf armor, the armadillo and renamed the scute to turtle_scute.

### CODE REVIEW

**Comment by atomic-junky** [comment]
I've also added the `supported_formats` line in pack.mcmeta to support all data pack versions from 6 to 41 (but i don't think the data pack work with older versions)

**Comment by HeDeAnTheonlyone** [comment]
Thanks for the pr. It helps a lot to maintain this project.

**Comment by atomic-junky** [comment]
Your project is really helpful, so I try to contribute a bit.
Btw I was wondering if it would be possible for you to update the datapack on ModRinth?

**Comment by HeDeAnTheonlyone** [comment]
I can do that, but it is very tedious to update it for every little change (at the moment it's not that much but I had times where I updated it multiple times a day for multiple days in a row). That's why I advise people to go get it here.

**Pull request merged**
